'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.PropertyAgent

    Partial Public Class CommentForm

        '''<summary>
        '''tblCommentForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCommentForm As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''rptDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptDetails As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''trCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trCaptcha As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptcha As Global.System.Web.UI.UserControl

        '''<summary>
        '''mlFlexCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mlFlexCaptcha As Global.Menulab.FlexCaptcha

        '''<summary>
        '''cmdSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSubmit As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblSubmitResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubmitResults As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
