'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace Ventrian.PropertyAgent

    '''<summary>
    '''EditTemplateDefinitions class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class EditTemplateDefinitions

        '''<summary>
        '''rptBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBreadCrumbs As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Options1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Options1 As Global.Ventrian.PropertyAgent.Options

        '''<summary>
        '''grdDefinitions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdDefinitions As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblNoTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoTemplates As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdImportNewTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdImportNewTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdChangeCurrentTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdChangeCurrentTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdExportCurrentTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdExportCurrentTemplate As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
