'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class EditPermissions

        '''<summary>
        '''rptBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBreadCrumbs As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Options1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Options1 As Global.Ventrian.PropertyAgent.Options

        '''<summary>
        '''dshPermissionSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshPermissionSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblPermissionSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPermissionSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblPermissionSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPermissionSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPermissions As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''grdPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPermissions As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblSubmitAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubmitAmount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dshPermissionAdvancedSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshPermissionAdvancedSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblPermissionAdvancedSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPermissionAdvancedSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plPermissionsAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPermissionsAdvanced As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''grdPermissionsAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPermissionsAdvanced As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblSubmitAmount2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubmitAmount2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDetailUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDetailUrl As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDetailUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDetailUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trAdminSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAdminSettings As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''dshAdminSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAdminSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblAdminSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAdminSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plAdminPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAdminPermissions As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''grdPermissionsAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPermissionsAdmin As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
