'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4959
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class EditLayoutFiles

        '''<summary>
        '''rptBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBreadCrumbs As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Options1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Options1 As Global.Ventrian.PropertyAgent.Options

        '''<summary>
        '''lblLayoutFilesUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLayoutFilesUpdated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dshEditLayoutFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshEditLayoutFiles As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblEditLayoutFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblEditLayoutFiles As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblEditLayoutFilesHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEditLayoutFilesHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCurrentTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCurrentTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblCurrentTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentTemplate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plLayoutGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLayoutGroups As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpLayoutGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpLayoutGroups As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblLayoutGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLayoutGroup As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trItem As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItem As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItem As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trAlternate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAlternate As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plAlternate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlternate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAlternate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlternate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trSeparator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSeparator As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSeparator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSeparator As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSeparator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeparator As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFooter As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFooter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trPhotoFirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPhotoFirst As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPhotoFirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhotoFirst As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPhotoFirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhotoFirst As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPhoto As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPhoto As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPhoto As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPageTitle As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPageTitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trPageDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPageDescription As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPageDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPageDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPageDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trPageKeywords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPageKeywords As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPageKeywords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPageKeywords As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPageKeywords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageKeywords As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trPageHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPageHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPageHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPageHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPageHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
