'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class EditPropertyNotifications

        '''<summary>
        '''rptBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBreadCrumbs As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Options1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Options1 As Global.Ventrian.PropertyAgent.Options

        '''<summary>
        '''dshPropertySettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshPropertySettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblPropertySettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPropertySettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblPropertySettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPropertySettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSubject As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plTemplateHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTemplateHeader As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTemplateHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTemplate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plTemplateFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTemplateFooter As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTemplateFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplateFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plToEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plToEmail As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtToEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valToEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valToEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plBCCEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBCCEmail As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtBCCEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBCCEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshSchedulerSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSchedulerSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblSchedulerSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSchedulerSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblSchedulerSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSchedulerSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSchedulerEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSchedulerEnabled As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnabled As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plTimeLapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTimeLapse As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTimeLapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTimeLapse As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpTimeLapseMeasurement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpTimeLapseMeasurement As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plRetryTimeLapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRetryTimeLapse As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRetryTimeLapse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRetryTimeLapse As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpRetryTimeLapseMeasurement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRetryTimeLapseMeasurement As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dshSchedulerHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSchedulerHistory As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblSchedulerHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSchedulerHistory As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblSchedulerHistoryHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSchedulerHistoryHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNoHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoHistory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dgScheduleHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgScheduleHistory As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
