'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class EditCustomField

        '''<summary>
        '''rptBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBreadCrumbs As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Options1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Options1 As Global.Ventrian.PropertyAgent.Options

        '''<summary>
        '''dshCustomFieldDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshCustomFieldDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblCustomFieldDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblCustomFieldDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblCustomFieldDetailsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomFieldDetailsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plName As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaption As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCaption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCaption As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plCaptionHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptionHelp As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCaptionHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCaptionHelp As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plFieldType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFieldType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpFieldType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpFieldType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFieldElements As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFieldElements As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstFieldElementType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstFieldElementType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''pnlFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFieldElements As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldElements As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valFieldElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valFieldElements As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''pnlFieldElementsType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFieldElementsType As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rptFieldElementsType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptFieldElementsType As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlFieldElementsDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFieldElementsDropDown As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''drpCustomFieldsDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCustomFieldsDropDown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rptFieldElementDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptFieldElementDropDown As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblFieldElementHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFieldElementHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFieldElementHelpStandard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFieldElementHelpStandard As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDefaultValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultValue As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDefaultValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDefaultValue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPublished As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPublished As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trMaximumLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trMaximumLength As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plMaximumLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaximumLength As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMaximumLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaximumLength As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaximumLengthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaximumLengthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''phRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phRequired As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshRequiredDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshRequiredDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblRequiredDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblRequiredDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblRequiredDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequiredDetails As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRequired As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRequired As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plValidationType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plValidationType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpValidationType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpValidationType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trRegex As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRegex As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegex As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''phLabelDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phLabelDetails As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshLabelDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshLabelDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblLabelDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblLabelDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblLabelDetailsDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabelDetailsDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLabelDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLabelDetails As DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''phSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSearch As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshSearchDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSearchDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSearchDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSearchDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plSearchDetailsDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchDetailsDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSearchable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchable As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSearchable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSearchable As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSearchType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trFieldElementsFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFieldElementsFrom As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFieldElementsFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFieldElementsFrom As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFieldElementsFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldElementsFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valFieldElementsFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valFieldElementsFrom As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblFieldElementsTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFieldElementsTo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trFieldElementsTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFieldElementsTo As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFieldElementsTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFieldElementsTo As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFieldElementsTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldElementsTo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valFieldElementsTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valFieldElementsTo As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lblFieldElementsFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFieldElementsFrom As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trIncludeCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trIncludeCount As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plIncludeCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeCount As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeCount As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trHideZeroCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trHideZeroCount As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plHideZeroCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideZeroCount As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideZeroCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideZeroCount As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''phDisplayDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDisplayDetails As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshDisplayDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshDisplayDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblDisplayDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDisplayDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblDisplayDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisplayDetails As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''trSortable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trSortable As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSortable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortable As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSortable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSortable As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFeatured As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plListing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plListing As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkListing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkListing As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plManager As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkManager As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCaptionHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptionHidden As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkCaptionHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCaptionHidden As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHidden As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHidden As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plLockDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLockDown As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkLockDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLockDown As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshSecurityDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSecurityDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblSecurityDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSecurityDetails As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblSecurityDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecurityDetails As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plInheritSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plInheritSecurity As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkInheritSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkInheritSecurity As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trEditRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trEditRoles As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plEditRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEditRoles As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstEditRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstEditRoles As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
