'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.PropertyAgent
    
    Partial Public Class LandingPage
        
        '''<summary>
        '''Options1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Options1 As Global.Ventrian.PropertyAgent.Options
        
        '''<summary>
        '''pnlSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''phProperty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phProperty As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
