'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class LatestOptions

        '''<summary>
        '''plModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleID As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plBubbleFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBubbleFeatured As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkBubbleFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkBubbleFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortBy As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortDirection As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plUserSortable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUserSortable As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkUserSortable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUserSortable As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSortFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortFields As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstSortFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstSortFields As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''dshFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshFilterSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblFilterSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plFilterSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFilterSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plType As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpTypes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plShowFeaturedOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowFeaturedOnly As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowFeaturedOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowFeaturedOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowShortListOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowShortListOnly As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowShortListOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowShortListOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCustomFields As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCustomFields As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtCustomField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomField As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''drpCustomField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCustomField As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkCustomField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCustomField As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkCustomFieldList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCustomFieldList As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''rdoCustomFieldList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoCustomFieldList As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''cmdAddCustomField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddCustomField As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''grdCustomFilters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCustomFilters As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''plStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStartDate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdStartDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''valStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valStartDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plMinAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMinAge As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMinAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinAge As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMinAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMinAge As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valMinAgeType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMinAgeType As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plMaxAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaxAge As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMaxAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxAge As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMaxAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxAge As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valMaxAgeType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxAgeType As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plUserFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUserFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstUserFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstUserFilter As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''trOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trOwner As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plSpecificUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSpecificUser As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpSpecificUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSpecificUser As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trParameter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trParameter As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plUserParameter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUserParameter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtUserParameter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserParameter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plShowRelated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowRelated As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowRelated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowRelated As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plRelatedCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRelatedCustomFields As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpRelatedCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpRelatedCustomFields As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshLayoutSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshLayoutSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblLayoutSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblLayoutSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblLayoutSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLayoutSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plMaxNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaxNumber As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtMaxNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaxNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valMaxNumberIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxNumberIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plEnablePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnablePager As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnablePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnablePager As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPageSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPageSize As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valPageSizeIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPageSizeIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plLayoutType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLayoutType As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstLayoutType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstLayoutType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''trItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trItemsPerRow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItemsPerRow As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemsPerRow As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valItemsPerRow As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valItemsPerRowIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valItemsPerRowIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLayoutMode As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstLayoutMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''trIncludeStylesheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trIncludeStylesheet As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plIncludeStylesheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeStylesheet As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeStylesheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeStylesheet As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trItem As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItem As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItem As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFooter As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFooter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFooter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trEmpty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trEmpty As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plEmpty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmpty As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmpty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmpty As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
