'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class SearchSmallOptions

        '''<summary>
        '''plModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLayoutMode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lstLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstLayoutMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''phLayoutStandard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phLayoutStandard As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''plSearchWildcard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchWildcard As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSearchWildcard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSearchWildcard As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSearchTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchTypes As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSearchTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSearchTypes As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSearchLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchLocation As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSearchLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSearchLocation As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSearchBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchBrokers As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSearchBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSearchBrokers As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSearchAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchAgents As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSearchAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSearchAgents As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCustomFields As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lstCustomFields control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstCustomFields As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''phLayoutCustom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phLayoutCustom As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''plSearchItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchItem As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSearchItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearchItem As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortBy As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSortDirection As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpSortDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSortDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshFormSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshFormSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblFormSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblFormSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblFormSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFormSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plHideHelpIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideHelpIcon As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideHelpIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideHelpIcon As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideTypeCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideTypeCount As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideTypeCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideTypeCount As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideZero control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideZero As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideZero control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideZero As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWidth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valWidthIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valWidthIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plRadioButtonItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRadioButtonItemsPerRow As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtRadioButtonItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRadioButtonItemsPerRow As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valRadioButtonItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRadioButtonItemsPerRow As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valRadioButtonItemsPerRowIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRadioButtonItemsPerRowIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plCheckBoxListItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCheckBoxListItemsPerRow As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCheckBoxListItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCheckBoxListItemsPerRow As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valCheckBoxListItemsPerRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCheckBoxListItemsPerRow As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valCheckBoxListItemsPerRowIsNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCheckBoxListItemsPerRowIsNumber As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plSearchStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchStyle As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSearchStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearchStyle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valSearchStyle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSearchStyle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plSplitRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSplitRange As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSplitRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSplitRange As Global.System.Web.UI.WebControls.CheckBox
    End Class
End Namespace
