'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class Search

        '''<summary>
        '''phSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSearch As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''pnlSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''trWildcard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trWildcard As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdHelpSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdHelpSearch As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imgHelpSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgHelpSearch As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblLabelSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabelSearch As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlHelpSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHelpSearch As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblHelpSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHelpSearch As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWildcard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWildcard As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trTypes As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTypes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdHelpTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdHelpTypes As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imgHelpTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgHelpTypes As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblLabelTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabelTypes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlHelpTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHelpTypes As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblHelpTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHelpTypes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''drpPropertyTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpPropertyTypes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLocation As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdHelpLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdHelpLocation As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imgHelpLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgHelpLocation As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblLabelLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabelLocation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlHelpLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHelpLocation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblHelpLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHelpLocation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trBrokers As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBrokers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdHelpBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdHelpBrokers As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imgHelpBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgHelpBrokers As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblLabelBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabelBrokers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlHelpBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHelpBrokers As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblHelpBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHelpBrokers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''drpPropertyBrokers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpPropertyBrokers As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAgents As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAgents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdHelpAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdHelpAgents As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''imgHelpAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgHelpAgents As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblLabelAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabelAgents As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlHelpAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHelpAgents As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblHelpAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHelpAgents As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''drpPropertyAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpPropertyAgents As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rptDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptDetails As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''cmdSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSearch As Global.Ventrian.PropertyAgent.LinkButtonDefault
    End Class
End Namespace
