'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class SendToFriendForm

        '''<summary>
        '''litEmailTo1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEmailTo1 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litEmailTo2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEmailTo2 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''phSendToFriendForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSendToFriendForm As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''tblSendToFriendForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSendToFriendForm As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''rptDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptDetails As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''cmdSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSubmit As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblSubmitResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubmitResults As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
