'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent

    Partial Public Class TypesOptions

        '''<summary>
        '''plModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleID As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plTypesSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTypesSortBy As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpTypesSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpTypesSortBy As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshFilterSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblFilterSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblFilterSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAgents As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdAddAgent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddAgent As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''rptAgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptAgents As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''lblNoAgentFitler control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoAgentFitler As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plHideZero control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideZero As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideZero control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideZero As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowTopLevelOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowTopLevelOnly As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowTopLevelOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowTopLevelOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowAllTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowAllTypes As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowAllTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowAllTypes As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trTypesFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trTypesFilter As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plTypesFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTypesFilter As Global.System.Web.UI.UserControl

        '''<summary>
        '''rptTypesFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptTypesFilter As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''dshLayoutSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshLayoutSettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblLayoutSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblLayoutSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLayoutMode As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstLayoutMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstLayoutMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''trIncludeStylesheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trIncludeStylesheet As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plIncludeStylesheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncludeStylesheet As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncludeStylesheet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncludeStylesheet As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trHeader As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeader As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trItem As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItem As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItem As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''trFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFooter As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFooter As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFooter As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
