'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Ventrian.PropertyAgent.Controls

    Partial Public Class EditPropertyPhotos

        '''<summary>
        '''dshAssignedPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAssignedPhotos As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblAssignedPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAssignedPhotos As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblAssignedPhotosHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAssignedPhotosHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdSortPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSortPhotos As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''phEditing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phEditing As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dlPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlPhotos As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''lblNoPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoPhotos As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phSorting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSorting As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblSortingInstructions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSortingInstructions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptPhotos As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
