'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.PropertyAgent.Controls

    Partial Public Class UploadPhotoSWF

        '''<summary>
        '''litModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litModuleID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTabModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTabModuleID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTicketID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTicketID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litPropertyGuid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPropertyGuid As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblSelectImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectImages As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dshUploadPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshUploadPhoto As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblUploadPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblUploadPhoto As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblUploadPhotoHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUploadPhotoHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImage As Global.System.Web.UI.UserControl

        '''<summary>
        '''trImageCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trImageCategories As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plImageCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImageCategories As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCategories As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshExternalPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshExternalPhoto As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblUploadExternalPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblUploadExternalPhoto As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblUploadExternalPhotoHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUploadExternalPhotoHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plExternalUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExternalUrl As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtExternalUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExternalUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdAttachPhoto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAttachPhoto As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''trImageCategoriesExternal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trImageCategoriesExternal As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plImageCategoriesExternal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImageCategoriesExternal As Global.System.Web.UI.UserControl

        '''<summary>
        '''drpCategoriesExternal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCategoriesExternal As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdRefreshPhotos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRefreshPhotos As Global.Ventrian.PropertyAgent.RefreshControl
    End Class
End Namespace
